[pytest]
addopts = -v --alluredir=allure-results
testpaths = api/tests ui/tests

markers =
    smoke: critical path tests
    regression: full regression suite
    api: REST API layer tests
    ui: UI browser tests
